### PR TITLE
Random_Numbers to Rmd

### PR DESCRIPTION
**Pull request by mcarlsn**
@jwokaty This is ready for your review. @villafup and @raoulkam tagging ya'll too if you're able to take a look. You will notice that I did not bump the version on the "Description" file. Also, I'm curious about your take on the author section @jwokaty. You'll see that the original file (https://bioconductor.org/packages/devel/bioc/vignettes/BiocParallel/inst/doc/Random_Numbers.pdf) has a hyperlinked footnote for the author. The author's name links to their website (https://www.roswellpark.org/martin-morgan). Apparently, in the newest version of RMarkdown no longer allows for footnotes in the title or author fields (see here for more info: https://github.com/rstudio/rmarkdown/issues/337). As an alternative, I tried creating a hyperlink but ran into problems because it's the author section. My final solution was to add the URL after the author's name. Looking forward to your feedback and thoughts. Thanks!

### CODE REVIEW

**Comment by villafup** [comment]
@mcarlsn Would this help?  I came across this a little bit ago and I think I got it to work.  Under "Endnotes" https://electricbookworks.github.io/electric-book/docs/editing/notes.html 

No idea how to get in on the side like the original.  And I found somewhere that you can use html, too.  Worth a google?

**Comment by villafup** [comment]
Doesn't work.  I think there's a conflict with Biocstyle.  Once I removed that reference in the yaml it rendered correctly.

**Comment by mcarlsn** [comment]
Thank you again, @villafup. I used your suggested code to update Random_Numbers with the author's affiliation and website. It is ready for review. Flagging @jwokaty @villafup and @raoulkam. Thanks, all.

**Comment by mtmorgan** [comment]
Thanks @mcarlsn ! I made several changes, summarized in this commit; the first (evaluate all code chunks) is important!

```
commit 0380225bc2f2502cacb0d8c5a3ada30455b32eba
Author: Martin Morgan <Martin.Morgan@RoswellPark.org>
Date:   Mon Aug 1 12:30:24 2022 -0400

    clean up vignette transition from Rnw to Rmd

    - Evaluate all code chunks, as in the original vignette
    - Use `r Biocpkg("BiocParallel")` (see BiocStyle vignette) to reference
      packages
    - Use email address rather than url for contact information. Using 'email:'
      with a url results in a 'mailto:' link that, when clicked on, will send
      to the url.
    - Title: and VignetteIndexEntry match Rnw, so the vignette appears in
      desired order when viewed with, e.g.,
      browseVignettes(package = "BiocParallel")
    - wrap and indent consistently (for my definition of consistent!)
```

**Pull request closed without merging**
